version: '3.8'

services:
  backend:
    build:
      context: ./task_organizer
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=task-organizer-db
      - DATABASE_USER=uolsauser
      - DATABASE_PASSWORD=$xnG%^;;fS;Eav.v
      - DATABASE_HOST=104.197.160.161
      - DATABASE_PORT=3306
    networks:
      - app-network

  frontend:
    build:
      context: ./task_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge
