# Generated by Django 5.1.3 on 2024-12-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_created_at_task_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='Descripción no proporcionada'),
        ),
    ]
